apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
      - name: practice-app-container
        image: practice-app-image:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 1000 
