apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "your-app-chart.fullname" . }}
data:
{{- range $key, $value := .Values.configMapValues }}
  {{ $key | quote }}: {{ $value | quote }}
{{- end }}
