name: Docker CI/CD

on:
  push:
    branches:
      - '*'
      - '!test'
    paths:
      - '**/*.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Branch Name as Environment Variable
      run: echo "DEPLOYED_FROM=${{ github.event_name }}-${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build & Push Docker Image
      run: |
        docker build -t Ashutosh1999/practice-app:latest .
        docker push Ashutosh1999/practice-app:latest

    - name: Deploy to k8s
      if: github.event_name != 'push' || github.ref_name != 'refs/heads/test'
      run: |
        kubectl apply -f Service.yaml
        kubectl apply -f Deployment.yaml 
        kubectl apply -f podSecurityPolicy.yaml
